-- @description Subharmonic Bank
-- @author s3g
-- @version 0.1
-- @requires ReaImGui; Python 3 with NumPy
-- @category Offline Synthesis / IR
-- @render Yes; renders a multichannel subharmonic oscillator bank.
-- @method Offline NumPy synthesis inspired by unstable subharmonic divider banks: root-driven divided voices, masks, drift, pulse/sine blend, fold, and multichannel spatial spread.

local script_path=({reaper.get_action_context()})[2]; local script_dir=script_path:match("^(.*[/\\])") or ""; local mc=dofile(script_dir.."Multichannel Library.lua"); local nr=dofile(script_dir.."NumPy Render Library.lua")
if not reaper.APIExists("ImGui_GetVersion") then reaper.MB("ReaImGui is not installed.","Subharmonic Bank",0) return end
package.path=reaper.ImGui_GetBuiltinPath().."/?.lua"; local ImGui=require("imgui")("0.10"); local EXT="s3g_mc_subharmonic_bank_v1"
local function getn(k,d)return tonumber(reaper.GetExtState(EXT,k))or d end; local function getb(k,d)local v=reaper.GetExtState(EXT,k);if v==""then return d end;return v~="0"end; local function set(k,v)reaper.SetExtState(EXT,k,type(v)=="boolean"and(v and"1"or"0")or tostring(v),true)end
local s={duration=getn("duration",12),channels=getn("channels",8),voices=getn("voices",24),root_freq=getn("root_freq",110),instability=getn("instability",0.12),pulse_blend=getn("pulse_blend",0.55),fold=getn("fold",0.2),event_mask=getn("event_mask",0.55),spatial_width=getn("spatial_width",1.8),normalize=getb("normalize",true),normalize_db=getn("normalize_db",-12),seed=getn("seed",1)}
local ctx=ImGui.CreateContext("Subharmonic Bank"); local open=true; local go=false
local function persist()for k,v in pairs(s)do set(k,v)end end
local function render()s.channels=math.max(1,math.min(mc.MAX_REAPER_TRACK_CHANNELS,math.floor(s.channels)));local stamp=tostring(math.floor(reaper.time_precise()*1000));local out_dir=nr.output_dir("s3g_subharmonic_bank_renders",nil,script_dir);local output_path=out_dir.."/s3g_subharmonic_bank_"..stamp.."_"..s.channels.."ch.wav";local manifest={output_path=output_path,sample_rate=48000,duration=s.duration,channels=s.channels,voices=s.voices,root_freq=s.root_freq,instability=s.instability,pulse_blend=s.pulse_blend,fold=s.fold,event_mask=s.event_mask,spatial_width=s.spatial_width,normalize=s.normalize,normalize_db=s.normalize_db,seed=s.seed};local log,elapsed=nr.run_backend(script_dir,"subharmonic_bank",manifest,"Subharmonic Bank");if not log then return end;reaper.Undo_BeginBlock();local item,err=nr.insert_output_item(output_path,"Subharmonic Bank ("..s.channels.."ch)",reaper.GetCursorPosition(),s.channels,{track_gain=0.35});reaper.Undo_EndBlock("Subharmonic Bank",-1);if not item then mc.show_error(err or"Could not insert render.")return end;mc.print_plan("Subharmonic Bank",{"Output: "..output_path,string.format("NumPy time: %.2f sec",elapsed),log})end
local function loop()ImGui.SetNextWindowSize(ctx,520,430,ImGui.Cond_Appearing);local vis;vis,open=ImGui.Begin(ctx,"Subharmonic Bank",open);if vis then local changed;changed,s.duration=ImGui.SliderDouble(ctx,"Duration sec",s.duration,0.5,180,"%.2f");changed,s.channels=ImGui.SliderInt(ctx,"Channels",math.floor(s.channels),1,mc.MAX_REAPER_TRACK_CHANNELS);changed,s.voices=ImGui.SliderInt(ctx,"Voices",math.floor(s.voices),1,96);changed,s.root_freq=ImGui.SliderDouble(ctx,"Root frequency",s.root_freq,20,880,"%.1f");changed,s.instability=ImGui.SliderDouble(ctx,"Instability",s.instability,0,1,"%.2f");changed,s.pulse_blend=ImGui.SliderDouble(ctx,"Pulse blend",s.pulse_blend,0,1,"%.2f");changed,s.fold=ImGui.SliderDouble(ctx,"Fold / drive",s.fold,0,1,"%.2f");changed,s.event_mask=ImGui.SliderDouble(ctx,"Mask openings",s.event_mask,0,1,"%.2f");changed,s.spatial_width=ImGui.SliderDouble(ctx,"Spatial width",s.spatial_width,0.2,8,"%.2f");changed,s.normalize=ImGui.Checkbox(ctx,"Peak normalize",s.normalize);if s.normalize then changed,s.normalize_db=ImGui.SliderDouble(ctx,"Normalize dB",s.normalize_db,-36,0,"%.1f")end;changed,s.seed=ImGui.InputInt(ctx,"Seed",math.floor(s.seed));if ImGui.Button(ctx,"Render",96,28)then go=true end;ImGui.SameLine(ctx);if ImGui.Button(ctx,"Cancel",96,28)then open=false end;ImGui.End(ctx)end;persist();if go then open=false;render();return end;if open then reaper.defer(loop)end end
reaper.defer(loop)
